/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ql.net.ui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import ql.net.util.XIcon;

/**
 *
 * @author ADMIN
 */
public class LoginJDialog extends javax.swing.JDialog {
    // Khai báo DAO ở đầu class (nếu chưa có)
    private ql.net.dao.NhanVienDao nhanVienDao = new ql.net.dao.impl.NhanVienDaoImpl();
    //biến kiểm tra đăng nhập
    private boolean loginSuccess = false;
    public boolean isLoginSuccess() {
        return loginSuccess;
    }
    //biến lưu nhân viên đăng nhập
    private ql.net.entity.NhanVien loggedNhanVien;
    public ql.net.entity.NhanVien getLoggedNhanVien() {
        return loggedNhanVien;
    }
    

    /**
     * Creates new form LoginJDialog
     */
    public LoginJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);//in ra giữa màn hình
        setupProportionalSize();//định dạng khung bằng với ảnh đã mặc định
    }
    
//    lấy khung bằng với ảnh
    private void setupProportionalSize() {
        // Lấy kích thước ảnh gốc
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/ql/net/icons/login.jpg"));
        int originalWidth = originalIcon.getIconWidth();
        int originalHeight = originalIcon.getIconHeight();

        // Tính tỷ lệ
        double ratio = (double) originalWidth / originalHeight;

        // Điều chỉnh kích thước dialog theo tỷ lệ ảnh
        int dialogWidth = 800;
        int dialogHeight = (int) (dialogWidth / ratio);

        // Giới hạn chiều cao tối đa
        if (dialogHeight > 700) {
            dialogHeight = 700;
            dialogWidth = (int) (dialogHeight * ratio);
        }

        setSize(dialogWidth, dialogHeight);
        setLocationRelativeTo(null);
        setResizable(false);

        // Scale ảnh theo kích thước mới
        jLabel2.setIcon(XIcon.getIcon("login.jpg", dialogWidth, dialogHeight));
        jLabel2.setBounds(0, 0, dialogWidth, dialogHeight);
        jPanel2.setBounds(0, 0, dialogWidth, dialogHeight);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đăng Nhập-Tấn Hiếu");
        setMaximumSize(new java.awt.Dimension(735, 413));
        setMinimumSize(new java.awt.Dimension(735, 413));
        setPreferredSize(new java.awt.Dimension(734, 410));
        setSize(new java.awt.Dimension(734, 400));
        getContentPane().setLayout(null);

        jPanel2.setMaximumSize(new java.awt.Dimension(735, 413));
        jPanel2.setMinimumSize(new java.awt.Dimension(735, 413));
        jPanel2.setPreferredSize(new java.awt.Dimension(734, 410));
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ĐĂNG NHẬP");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(280, 70, 240, 50);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên đăng nhập:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(100, 170, 130, 30);

        txtTenDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(txtTenDangNhap);
        txtTenDangNhap.setBounds(240, 170, 430, 35);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mật khẩu:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(130, 240, 90, 25);

        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(txtMatKhau);
        txtMatKhau.setBounds(240, 240, 430, 35);

        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        jPanel2.add(btnDangNhap);
        btnDangNhap.setBounds(470, 330, 110, 31);

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel2.add(btnThoat);
        btnThoat.setBounds(600, 330, 76, 31);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ql/net/icons/user.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 160, 40, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ql/net/icons/password.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 230, 32, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ql/net/icons/login.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(734, 410));
        jLabel2.setRequestFocusEnabled(false);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 740, 440);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 734, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        String username = txtTenDangNhap.getText().trim();
        String password = new String(txtMatKhau.getPassword()).trim();
        // Kiểm tra đăng nhập từ database
        ql.net.entity.NhanVien nv = nhanVienDao.login(username, password);
        if (nv != null) {
            loginSuccess = true;
            loggedNhanVien = nv;
            dispose();
        } 
        else {
            loginSuccess = false;
            JOptionPane.showMessageDialog(this,
                "Sai tài khoản hoặc mật khẩu!",
                "Đăng nhập thất bại",
                JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginJDialog dialog = new LoginJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
