/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ql.net.ui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class RechargeJDialog extends javax.swing.JDialog {
    
    // Biến lưu thông tin khách hàng
    private String maKHDuocChon;
    private String hoTenKH;
    private String soDTKH;
    private String soDuHienTai;
    private javax.swing.JTable tblLichSuGiaoDich;

    /**
     * Creates new form RechargeJDialog
     */
    public RechargeJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);//in ra giữa màn hình
        setupForm();
    }
    
    // Thiết lập form ban đầu
    private void setupForm() {
        // Generate mã nạp tiền tự động
        txtMaNapTien.setText(generateMaNapTien());
        
        // Set ngày hiện tại
        dateNgayNhap.setDate(new java.util.Date());
        
        // Disable các field không cho edit
        txtMaNapTien.setEditable(false);
        txtMaKH.setEditable(false);
        txtMaNV.setEditable(false);
        
        // Set background cho các field readonly
        java.awt.Color readOnlyColor = new java.awt.Color(240, 240, 240);
        txtMaNapTien.setBackground(readOnlyColor);
        txtMaKH.setBackground(readOnlyColor);
        txtMaNV.setBackground(readOnlyColor);
        
        // Focus vào số tiền nạp
        txtSoTienNap.requestFocus();
    }
    
    // Method nhận thông tin khách hàng từ HomeJFrame
    public void setThongTinKhachHang(String maKH, String hoTen, String soDT, String soDu) {
        this.maKHDuocChon = maKH;
        this.hoTenKH = hoTen;
        this.soDTKH = soDT;
        this.soDuHienTai = soDu;
        
        // Hiển thị thông tin lên form
        txtMaKH.setText(maKH);
        
        // Cập nhật title của dialog
        setTitle("Nạp tiền cho khách hàng: " + hoTen + " (" + maKH + ")");
        
        // Thêm tooltip để hiển thị thông tin đầy đủ
        txtMaKH.setToolTipText("Khách hàng: " + hoTen + " - SĐT: " + soDT + " - Số dư: " + soDu + " VNĐ");
        
        System.out.println("✅ Đã set thông tin KH: " + maKH + " - " + hoTen);
    }
    
    // Method nhận thông tin nhân viên
    public void setThongTinNhanVien(String maNV, String tenNV) {
        txtMaNV.setText(maNV);
        txtMaNV.setToolTipText("Nhân viên: " + tenNV);
        
        System.out.println("✅ Đã set thông tin NV: " + maNV + " - " + tenNV);
    }
    
    // Generate mã nạp tiền tự động
    private String generateMaNapTien() {
        try {
            String sql = "SELECT COUNT(*) as total FROM NapTien";
            String count = ql.net.util.XJdbc.getValue(sql);
            int nextNumber = Integer.parseInt(count != null ? count : "0") + 1;
            return String.format("NT%03d", nextNumber);
        } catch (Exception e) {
            // Fallback với timestamp
            return "NT" + String.format("%03d", (int)(System.currentTimeMillis() % 1000));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaNapTien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dateNgayNhap = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txtSoTienNap = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cboHinhThucNap = new javax.swing.JComboBox<>();
        btnThoat = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("NẠP TIỀN");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ql/net/icons/nap_tien_qr.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setText("Mã nạp tiền:");

        jLabel4.setText("Mã khách hàng:");

        jLabel5.setText("Mã nhân viên:");

        jLabel6.setText("Ngày nhập:");

        jLabel7.setText("Số tiền nạp:");

        jLabel8.setText("Hình thức nạp:");

        cboHinhThucNap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Chuyển khoản" }));

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(btnThanhToan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnThoat))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaNapTien)
                                            .addComponent(txtMaKH)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel5)))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSoTienNap, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(dateNgayNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtMaNV)
                                            .addComponent(cboHinhThucNap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaNapTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(dateNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSoTienNap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboHinhThucNap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat)
                    .addComponent(btnThanhToan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        if (validateFormNapTien()) {
            xuLyNapTien();
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    // Validation form
    private boolean validateFormNapTien() {
        // Kiểm tra mã khách hàng
        if (txtMaKH.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa có thông tin khách hàng!");
            return false;
        }
        
        // Kiểm tra số tiền nạp
        if (txtSoTienNap.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số tiền nạp!");
            txtSoTienNap.requestFocus();
            return false;
        }
        
        try {
            double soTien = Double.parseDouble(txtSoTienNap.getText().replace(",", ""));
            if (soTien <= 0) {
                JOptionPane.showMessageDialog(this, "Số tiền nạp phải lớn hơn 0!");
                txtSoTienNap.requestFocus();
                return false;
            }
            if (soTien > 50000000) { // Giới hạn 50 triệu
                JOptionPane.showMessageDialog(this, "Số tiền nạp không được vượt quá 50,000,000 VNĐ!");
                txtSoTienNap.requestFocus();
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số tiền nạp không hợp lệ!");
            txtSoTienNap.requestFocus();
            return false;
        }
        
        return true;
    }
    
    // Xử lý nạp tiền
    private void xuLyNapTien() {
        try {
            String maNapTien = txtMaNapTien.getText();
            String maKH = txtMaKH.getText();
            String maNV = txtMaNV.getText();
            double soTienNap = Double.parseDouble(txtSoTienNap.getText().replace(",", ""));
            String hinhThuc = (String) cboHinhThucNap.getSelectedItem();
            
            // Tính số dư mới
            double soDuCu = Double.parseDouble(soDuHienTai.replace(",", ""));
            double soDuMoi = soDuCu + soTienNap;
            
            // Dialog xác nhận
            String confirmMessage = String.format(
                "Xác nhận nạp tiền?\n\n" +
                "📋 THÔNG TIN NAP TIỀN:\n" +
                "👤 Khách hàng: %s (%s)\n" +
                "💰 Số tiền nạp: %,.0f VNĐ\n" +
                "💳 Hình thức: %s\n" +
                "💵 Số dư hiện tại: %,.0f VNĐ\n" +
                "💵 Số dư sau nạp: %,.0f VNĐ\n" +
                "👨‍💼 Nhân viên: %s",
                hoTenKH, maKH, soTienNap, hinhThuc, soDuCu, soDuMoi, maNV
            );
            
            int confirm = JOptionPane.showConfirmDialog(this, confirmMessage, 
                "Xác nhận nạp tiền", JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION) {
                // 1. Thêm vào bảng NapTien
                String sqlNapTien = "INSERT INTO NapTien (MaNapTien, MaKH, MaNV, SoTienNap, HinhThucNap) VALUES (?, ?, ?, ?, ?)";
                boolean okNapTien = ql.net.util.XJdbc.executeUpdate(sqlNapTien, 
                    maNapTien, maKH, maNV, 
                    java.math.BigDecimal.valueOf(soTienNap), 
                    hinhThuc) > 0;
                
                // 2. Cập nhật số dư tài khoản khách hàng
                String sqlUpdateKH = "UPDATE KhachHang SET SoDuTaiKhoan = SoDuTaiKhoan + ? WHERE MaKH = ?";
                boolean okUpdateKH = ql.net.util.XJdbc.executeUpdate(sqlUpdateKH, 
                    java.math.BigDecimal.valueOf(soTienNap), maKH) > 0;
                
                // 3. Thêm vào lịch sử giao dịch
//                String maGD = generateMaGiaoDich();
//                String sqlLichSu = "INSERT INTO LichSuGiaoDich (MaGiaoDich, MaKH, LoaiGiaoDich, SoTien) VALUES (?, ?, N'Nạp tiền', ?)";
//                boolean okLichSu = ql.net.util.XJdbc.executeUpdate(sqlLichSu, 
//                    maGD, maKH, java.math.BigDecimal.valueOf(soTienNap)) > 0;
//                
//                if (okNapTien && okUpdateKH && okLichSu) {
//                    // Thông báo thành công
//                    JOptionPane.showMessageDialog(this, 
//                        String.format("✅ NẠP TIỀN THÀNH CÔNG!\n\n" +
//                            "👤 Khách hàng: %s\n" +
//                            "💰 Số tiền nạp: %,.0f VNĐ\n" +
//                            "💵 Số dư mới: %,.0f VNĐ\n" +
//                            "🎫 Mã giao dịch: %s", 
//                            hoTenKH, soTienNap, soDuMoi, maGD),
//                        "Nạp tiền thành công", JOptionPane.INFORMATION_MESSAGE);
//                    
//                    // Đóng dialog
//                    dispose();
//                    
//                } else {
//                    JOptionPane.showMessageDialog(this, "❌ Lỗi nạp tiền! Vui lòng thử lại.");
//                }
                String maGD = generateMaGiaoDich();
                String sqlLichSu = "INSERT INTO LichSuGiaoDich (MaGiaoDich, MaKH, LoaiGiaoDich, SoTien) VALUES (?, ?, N'Nạp tiền', ?)";
                boolean okLichSu = ql.net.util.XJdbc.executeUpdate(sqlLichSu, maGD, maKH, java.math.BigDecimal.valueOf(soTienNap)) > 0;

                if (okNapTien && okUpdateKH && okLichSu) {
                    JOptionPane.showMessageDialog(this, "✅ NẠP TIỀN THÀNH CÔNG!");
                    // Sau khi nạp tiền thành công, gọi hàm cập nhật lịch sử giao dịch trên giao diện
                    if (getParent() instanceof HomeJFrame) {
                        ((HomeJFrame)getParent()).loadLichSuGiaoDichToTable();
                    }
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "❌ Lỗi nạp tiền! Vui lòng thử lại.");
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi nạp tiền: " + e.getMessage());
        }
    }
    
    public void loadLichSuGiaoDichToTable() {
        try {
            String sql = "SELECT MaGiaoDich, MaKH, LoaiGiaoDich, SoTien, NgayGiaoDich FROM LichSuGiaoDich ORDER BY NgayGiaoDich DESC";
            java.sql.ResultSet rs = ql.net.util.XJdbc.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel) tblLichSuGiaoDich.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("MaGiaoDich"),
                    rs.getString("MaKH"),
                    rs.getString("LoaiGiaoDich"),
                    rs.getBigDecimal("SoTien"),
                    rs.getTimestamp("NgayGiaoDich")
                });
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tải lịch sử giao dịch: " + e.getMessage());
        }
    }
    
    // Generate mã giao dịch
    private String generateMaGiaoDich() {
        try {
            String sql = "SELECT COUNT(*) as total FROM LichSuGiaoDich";
            String count = ql.net.util.XJdbc.getValue(sql);
            int nextNumber = Integer.parseInt(count != null ? count : "0") + 1;
            return String.format("GD%04d", nextNumber);
        } catch (Exception e) {
            return "GD" + String.format("%04d", (int)(System.currentTimeMillis() % 10000));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RechargeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RechargeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RechargeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RechargeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RechargeJDialog dialog = new RechargeJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cboHinhThucNap;
    private com.toedter.calendar.JDateChooser dateNgayNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaNapTien;
    private javax.swing.JTextField txtSoTienNap;
    // End of variables declaration//GEN-END:variables
}
